### ISSUE TITLE
libxsd error

### ISSUE THREAD

**Issue by leachim** [TUM-I5/MolSim#2]
./libxsd/xsd/cxx/tree/parsing.txx 
./libxsd/xsd/cxx/zc-istream.txx

error:  was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

solution:  
./libxsd/xsd/cxx/tree/parsing.txx 
302,13 and 312,13: change push_back to this->push_back

./libxsd/xsd/cxx/zc-istream.txx
35,7 change setg to this->setg

**Comment by FG-TUM** [comment]
fixed in a257438d3805fae6a6e3d571a1065cbf17dd8a7c
